
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SocketProvider } from "@/helpers/useSocket";
import { Toaster } from "react-hot-toast";
import { WebRTC } from "./videochat/component/WebRTC";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster/>
        <SocketProvider serverUrl={process.env.NEXT_PUBLIC_SERVER_URL}>
          <WebRTC>
        {children}
        </WebRTC>
        </SocketProvider>
      </body>
    </html>
  );
}
